version: '3.0'
services:
  web:
    image: local/gitweb
    ports:
      - "30080:80"
      - "30022:22"
    volumes:
      - ./env:/.env
      - repos:/git
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  repos: {}
